
name: CBS Automation Test

on:
  workflow_dispatch:

# Permissions for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping queued runs
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    services:
      xvfb:
        image: selenium/standalone-chrome
        options: --health-cmd "curl --silent --fail localhost:4444/wd/hub/status || exit 1"
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Set up Maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9
      
      # Set up JDK 22
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'oracle'

          
  
      - name: Run Test
        run: export DISPLAY=:99 && mvn test
        continue-on-error: true

      # Download and install Allure
      - name: Download Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure_2.18.1-1_all.deb
          sudo dpkg -i allure_2.18.1-1_all.deb

      # Generate Allure Report
      - name: Generate Allure Report
        run: |
          allure generate target/allure-results --clean -o build/allure-report

      # # Ensure the Allure report directory doesn't contain symlinks
      # - name: Remove symlinks from Allure report
      #   run: |
      #     find build/allure-report -type l -exec cp --remove-destination {} {} \;
      - name: Check files
        run: |
          pwd
          ls -la

      - name: Upload screenshots as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: |
            ./src/main/resources/application.properties
          retention-days: 15
          
#./screenshots

      # Set up GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: gh-pages
          path: './build/allure-report'

     # Deploy Allure Report to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: gh-pages

      # Send Allure Report via Email (Optional)
      - name: Send Email with Allure Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Allure Test Report - CBS Automation"
          body: |
            Hello,
      
            The latest Allure Test Report is available at:
            🔗 [CBS Automation Report](https://rahulsaini62.github.io/cbs_automation/)
      
            Thanks.
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.EMAIL_USERNAME }}
